name: Process Email Queue

on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  process-queue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Process Email Queue
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.VERCEL_URL }}/api/queue/process-all"
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}

      - name: Log Result
        if: always()
        run: echo "Queue processing completed at $(date)"